### ISSUE TITLE
Question about "optimal_span" documentation

### ISSUE THREAD

**Issue by benjaminrobinson** [khufkens/phenocamr#26]
Hi!  I am intrigued by the "optimal_span" function you have written because I'm looking for a way to find the optimal span for a series of loess regressions I'm running.

In your documentation for the function, you write in the code "Internal function only, should not be used stand-alone."  Could you explain if you mean I shouldn't use this function by itself or something else?  Also, if possible could you please explain why this is the case?  Thanks!  Appreciate the work!
https://github.com/khufkens/phenocamr/blob/cd1ed0b708b551852830a22ab7cb772cddefd87a/R/optimal_span.r

**Comment by khufkens** [comment]
This just means that the code is not well documented and the approach stable. I generally will not touch this code unless there is a severe bug. In part because it affects a lot of the processing in the package (down the line) and the yearly product releases based upon the code.

In practice this means that you can use this function on its own, but I will not provide support for it.  Normally it should work with any combination of y/x values regardless of their origin.
